Repository KendallDoesCoding/Choose-Your-Own-Adventure-Game, pull requests merged in 2022-08, with the labels that each got.

#7 grammerfixed
  README.md
Labels: size/S

#8 adds issue templates
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: size/L

#9 [Refactoring]: Seperation into chapters
  main.py
Labels: size/L

#11 added the link for contributing guideline in README
  CONTRIBUTING.md
  README.md
Labels: size/L

#12 addedpolicies
  security.md
Labels: size/XS

#13 GRAMMAR CHANGE AND FORMATTING CHANGE
  CONTRIBUTING.md
  README.md
Labels: size/M

#14 ADD VIDEO FILE TO README
  README.md
Labels: size/XS
