Repository KendallDoesCoding/Choose-Your-Own-Adventure-Game, pull requests merged in 2023-03, with the labels that each got.

#23 fixed typo on chapters.py
  chapters.py
Labels: size/S

#25 Bug fix
  __pycache__/chapters.cpython-310.pyc
  __pycache__/music.cpython-310.pyc
  chapters.py
Labels: size/XS

#34 Loop Music
  chapters.py
  main.py
  music.py
  music/__init__.py
  music/musicTimer.py
  music_player.py
Labels: size/XL

#43 Made changes into chapter.py file
  chapters.py
Labels: size/S

#44 Gitpod
  .gitpod.yml
  main.py
  package-lock.json
  requirements.txt
Labels: size/S

#47 New Chapter Added
  chapters.py
Labels: size/M

#49 Add GUI
  GUI/GUI.py
  GUI/GUIObjects.py
  README.md
  assets/images/MusicOff.png
  assets/images/MusicOn.png
  assets/images/landscape.png
  chapters.py
  main.py
  music/__init__.py
  music_player.py
  requirements.txt
Labels: size/XXL

#58 Replaced exit() with sys.exit(1)
  GUI/GUI.py
Labels: size/XS

#59 Refactoring
  GUI/GUI.py
  GUI/GUIObjects.py
  main.py
  music_player.py
Labels: size/L
